version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15.3-alpine
    container_name: customer-profile-postgres
    environment:
      POSTGRES_DB: customer_profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Cassandra Database
  cassandra:
    image: cassandra:4.1
    container_name: customer-profile-cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=CustomerProfileCluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_DC=datacenter1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe cluster' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5

  # PgAdmin for PostgreSQL Management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # CQLSH for Cassandra Management
  cqlsh:
    image: cassandra:4.1
    container_name: cqlsh
    depends_on:
      - cassandra
    entrypoint: ["cqlsh", "cassandra"]
    tty: true
    stdin_open: true

  # Application Service
  customer-profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-profile-service
    ports:
      - "8090:8090"
    environment:
      # PostgreSQL Configuration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customer_profile_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      
      # Cassandra Configuration
      - SPRING_DATA_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_DATA_CASSANDRA_PORT=9042
      - SPRING_DATA_CASSANDRA_KEYSPACE=customer_profile_ks
      - SPRING_DATA_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_DATA_CASSANDRA_USERNAME=cassandra
      - SPRING_DATA_CASSANDRA_PASSWORD=cassandra
    depends_on:
      postgres:
        condition: service_healthy
      cassandra:
        condition: service_healthy

volumes:
  postgres_data:
  cassandra_data:
