global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Reservation System
  - job_name: 'reservation-system'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['reservation-system:8080']
    scrape_timeout: 10s

  # Redis Exporter (if you add it later)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Exporter (if you add it later)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Cassandra Exporter (if you add it later)
  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra:9042']
    metrics_path: '/metrics'
    scrape_interval: 30s
