spring:
  cassandra:
    keyspace-name: reservation_system
    contact-points: 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    schema-action: create-if-not-exists
  
  # PostgreSQL configuration for JPA entities
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

# Actuator and Metrics Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: reservation-system
      environment: development

logging:
  level:
    com.reservation.service: DEBUG
    org.springframework.data.cassandra: DEBUG
